[package]
name = "rs-stellar-token-contract"
version = "0.0.0"
authors = ["Stellar Development Foundation <info@stellar.org>"]
license = "Apache-2.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
stellar-contract-sdk = { git = "https://github.com/stellar/rs-stellar-contract-sdk", rev = "1bf6da3" }

[dev_dependencies]
stellar-contract-sdk = { git = "https://github.com/stellar/rs-stellar-contract-sdk", rev = "1bf6da3", features = ["testutils"] }
