[package]
name = "stellar-token-contract"
version = "0.0.0"
authors = ["Stellar Development Foundation <info@stellar.org>"]
license = "Apache-2.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# stellar-contract-sdk = { git = "https://github.com/stellar/rs-stellar-contract-sdk", rev = "b7af766" }
stellar-contract-sdk = { path = "../rs-stellar-contract-sdk/sdk" }

[dev_dependencies]
ed25519-dalek = "1.0.1"
num-bigint = "0.4"
rand = "0.7.3"
sha2 = "0.10.2"
# stellar-contract-sdk = { git = "https://github.com/stellar/rs-stellar-contract-sdk", rev = "b7af766", features = ["testutils"] }
stellar-contract-sdk = { path = "../rs-stellar-contract-sdk/sdk", features = ["testutils"] }
stellar-xdr = { git = "https://github.com/stellar/rs-stellar-xdr", rev = "db2ca71", features = ["next", "std"] }
